pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git 'https://github.com/Mahadevlt01/repo1.git'
            }
        }
        stage("Maven Build"){
            steps{
                sh "mvn package"
            }
        }
    }
}

