pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git 'https://github.com/Mahadevlt01/repo1.git'
            }
        }
        stage("Maven Build"){
            steps{
                def mvnHome = tool name: 'MyMaven', type: 'maven'
                
                sh "${mvnHome}/bin/mvn clean package"
            }
        }
    }
}

